### PR TITLE
Format / refactor code to PSR standards, introduce exceptions, update documentation

### PR DESCRIPTION
**Pull request by arkamax2k**
Code was reformatted to match PSR standards. Exceptions were introduced to assist with error handling. API responses were modeled in a response object to assist with property access and reduce potential for typos and errors. A composer.json file was introduced to allow installation via Composer (and hopefully later Packagist). Documentation was updated to match.

### CODE REVIEW

**Comment by apexdodge** [comment]
This is pretty great, and counter-intuitively, almost too great. My main concern from an operations standpoint is that I get many support requests from developers who are brand new or have very limited experience in writing code. Strangely, I've had developers just want me to write code for them too. The benefit from the other way is that it's just a single php file, drop it in and you're good to go which tends to simplify things.

Would your code work as-is for those that don't know how to use composer? Basically copy the files, type:

    require('Api2Pdf.php'); 

and be good to go? Or is composer an absolute prerequisite?

Thanks for the great work on this.

**Comment by arkamax2k** [comment]
I'm glad you liked it! Composer is not an absolute pre-requisite (in fact I tested it without using one) - it is however the industry standard in PHP development these days, because it removes a lot of headaches. That said, if one did want to not use Composer, it would be sufficient to require two files. Note that I'd recommend using require_once() instead as it avoid duplicate inclusions and related issues. 

`
require_once 'api2pdf.php/src/Api2Pdf.php';
require_once 'api2pdf.php/src/ApiResult.php';

use Api2Pdf\Api2Pdf;
use Api2Pdf\ApiResult;

$api = new Api2Pdf("<API_KEY>");
` 
Then, if they wanted to catch exceptions without regard to type, they can simply catch \Exception class. To distinguish between different classes, they can optionally require_once() (and "use", if desired to cut on namespace prefixing) relevant exception classes - although that is not a requirement for basic use. 

However, I would highly advocate for using Composer - if someone is not using it, they seriously need to consider it, given all the benefits it brings.

**Comment by arkamax2k** [comment]
P.S. I added the relevant example to the README (and fixed an omission in the same file while at it). Hope that works.

**Comment by apexdodge** [comment]
Much appreciated. I'll finish my review this weekend and merge the pull request if no other action needed.

**Comment by arkamax2k** [comment]
If it gets in, I'd also recommend doing the following: 

1. Tagging the repo with a version, e.g. v1.0.0. Doing so would help Composer folks, especially if you consider...

2. Adding the repo to Packagist: https://packagist.org/packages/submit - once that's done, anyone can pull it with literally a single line added to their composer.json file.

**Comment by arkamax2k** [comment]
@apexdodge , oops, sorry, my bad - I made a change as suggested. Let me know if you run into any other issues.

**Pull request merged**
